### PR TITLE
Remove enumerations from stats_enums.hpp that are not used

### PR DESCRIPTION
**Pull request by RickiNano**
Clean up enumerations that are no longer in use. This pr targets #4102

### CODE REVIEW

**Comment by gr0vity-dev** [comment]
I'm wondering if it makes sense to have enums that are only used in the testcases ?
Do they make sense in a testcase when the codebase doesn't use them ?

Looking at the `vote_processed` enum, it got removed with the Optimistic elections PR in these commits :
[e1c893b7dcbcfd9cf53eb1b0239e9febc62bb508](https://github.com/nanocurrency/nano-node/commit/e1c893b7dcbcfd9cf53eb1b0239e9febc62bb508)
[62811054380185c376df600501d22101b389d975](https://github.com/nanocurrency/nano-node/commit/62811054380185c376df600501d22101b389d975)

**Comment by clemahieu** [comment]
> I'm wondering if it makes sense to have enums that are only used in the testcases ? Do they make sense in a testcase when the codebase doesn't use them ?
> 
> Looking at the `vote_processed` enum, it got removed with the Optimistic elections PR in these commits : [e1c893b7dcbcfd9cf53eb1b0239e9febc62bb508](https://github.com/nanocurrency/nano-node/commit/e1c893b7dcbcfd9cf53eb1b0239e9febc62bb508) [62811054380185c376df600501d22101b389d975](https://github.com/nanocurrency/nano-node/commit/62811054380185c376df600501d22101b389d975)

That is a good point and really I agree. It's occurred to me that we shouldn't be checking counters in tests at all. The stat counters are for users, and just as we shouldn't be depending on the output of logs, we shouldn't be depending on the counters.

**Comment by RickiNano** [comment]
Do you want me to remove the enums again, and also remove the unit tests they are used in?

**Comment by clemahieu** [comment]
No, let's do that separately.  This change is fine on its own to remove enums that are completely unused.

**Pull request merged**
