### PR TITLE
RPC node_config

### PR DESCRIPTION
**Pull request by guilhermelawless**
Useful for users/services to not have to parse `config.json` themselves.

Usage:
```json
{"action": "node_config"}
```

### CODE REVIEW

**Comment by rkeene** [comment]
How do you feel about adding an additional optional attribute to fetch a subset of the config, or a single attribute ?

**Comment by guilhermelawless** [comment]
@rkeene would be useful. How about:

```json
{"action": "node_config", "field": "logging.version"}
```

Not sure what to name the optional. Is it still an attribute if it's not a leaf?

**Comment by guilhermelawless** [comment]
@rkeene Some design decisions and constraints to allow getting subset of config:

- To accept `logging` that case had to be specified to serialize. Will need to do the same if similar cases appear in the future
- Without looking for last separator (`.`) and finding the substring, the response would be e.g. `{"logging": {"log_rpc": "true"}"}` when asking for "logging.log_rpc", defeating the purpose of specifying a subset. The actual response is `{"log_rpc": "true"}`

If you think the current design is fine then i'll do some unit tests.

**Comment by guilhermelawless** [comment]
Much more elegant @cryptocode thank you. But i find it a bit inconsistent that asking for nothing gets a field "node", asking for logging gets a field "logging" and asking for a leaf, like "logging.version", gets a field "value".

Is there an easy way to get the last part of the path?

**Comment by cryptocode** [comment]
@guilhermelawless see https://en.cppreference.com/w/cpp/string/basic_string/find_last_of for how to extract the last part of the path, if you want that instead of "value".

**Comment by guilhermelawless** [comment]
@cryptocode Ok I had it that before, put it back. Should be ready now, tests included.

**Comment by zhyatt** [comment]
After further discussion with the team and @guilhermelawless it was determine the usefulness of this approach vs. directly parsing the config file did not warrant including the change, so we are closing this one out.

**Pull request closed without merging**
