### PR TITLE
Migrate LMDB database to RocksDB with new CLI command

### PR DESCRIPTION
**Pull request by wezrule**
This adds a new CLI command `--migrate_database_lmdb_to_rocksdb` which takes the LMDB database, deletes the RocksDB folder if it exists and creates an equivalent RocksDB ledger.

This adds the necessary parallel for loops for the required tables, should be rebased after https://github.com/nanocurrency/nano-node/pull/2950 is in.

### CODE REVIEW

**Comment by guilhermelawless** [comment]
Mainnet migration at ~55M blocks:
- 19GB at the end from a 30GB data.ldb, took 13 minutes on a Ryzen 3600 and NVME SSD, 16GB RAM
- 19GB at the end from a 22GB data.ldb, took 28 minutes on a i5-6600 and SATA SSD, 8GB RAM

Second one produced a message "There was an error migrating" but everything seems fine after migrating, investigating.

**Comment by SergiySW** [comment]
22GB from 21GB data.ldb. 29 minutes on i7-4970K and SATA SSD. 16GB RAM

**Review by SergiySW — APPROVED** [review]

**Comment by qwahzi** [comment]
Worked nicely for me on V22DB11, even without being fully synced (had ~1.7M blocks), took ~5 minutes to convert. First launch afterwards was still LMDB, but then I realized I needed to update my config-node.toml. Should this be done by default for v22+? I'm assuming RocksDB will be the preferred production backend

`[node.rocksdb]
# Whether to use the RocksDB backend for the ledger database.
# type:bool
enable = true`

**Comment by ghost** [comment]
Successful on 22DB11, 4 minutes. 4670k@4.5ghz, 16GB, 1TB sata SSD. Ledger 5.8GB to 3.5GB. Ubuntu 20.04.2

**Pull request merged**
