### PR TITLE
Clean up ledger::process return value.

### PR DESCRIPTION
**Pull request by clemahieu**
Remove process_return class which only contained process_result.
Rename process_result to block_status to better indicate its purpose.

### CODE REVIEW

**Comment by RickiNano** [comment]
I'm new to the codebase so it may just be me who is confused, but I find the name ledger_code to be confusing and not descriptive of what it is. The word "code" is very generic and can be so many things.
How about ledger_result? Or ledger_status?
Or if code needs to be in the name, then ledger_result_code or ledger_status_code

**Comment by clemahieu** [comment]
I think a longer name here is overly descriptive. The main c++ type to report errors is std::error_code so I think nano::ledger_code matches this.

I would have made this a nested enum of ledger nano::ledger::code, though nested types cannot be forward declared so I named it nano::ledger_code.

This is some external discussion on overly long names: https://wiki.c2.com/?VeryLongDescriptiveNamesThatProgrammingPairsThinkProvideGoodDescriptions

**Comment by RickiNano** [comment]
I was not advocating for longer naming per se, but just replacing "code" with "status" or "result" that has more meaning (at least to me :) )

**Comment by clemahieu** [comment]
Changed to nano::block_status

**Pull request merged**
