### PR TITLE
Make work faster

### PR DESCRIPTION
**Pull request by DanielMazurFL4RE**
Current PoW take too much time to calculate on smartphones or regular machines, I've spent few days writing own optimized "miner", checked few PoW scripts (like this written in WASM) and they takes approx. 40 seconds to mine on PC and approx. 120 seconds on regular smartphone.
How this coin may be adopted by masses If guy who want to pay for coffee must stay by shop counter 2 minutes?

We need to find other way to prevent spam attacks!

### CODE REVIEW

**Comment by wezrule** [comment]
PoW can be precomputed for the next block so for everyday transactions like getting coffee it should not be problem. For services requiring high throughput and also done server side using dPoW.

**Comment by DanielMazurFL4RE** [comment]
Alright but what if I have few pending blocks or want to send NANOs few times?
As you can see, then it may take long time if user have no luck and won't time valid work in few first seconds

**Comment by rotilho** [comment]
How avoid spam in this case? Just reduce the difficult can create a even bigger problem.

Keep the wallet open for while (and using dPoW or Work Server) sounds quite reasonable for me and payment processors will have good hardware to compute pow and they can also shard their wallet to increase TPS.

**Comment by zhyatt** [comment]
@DanielMazurFL4RE Thanks for submitting. The PoW is meant to be a spam reduction mechanism so reducing difficulty decreases protection against spam. At this time we are not interested in doing so, so closing this ticket. In the future if we decide this is an option we can reopen and evaluate.

**Pull request closed without merging**
