### PR TITLE
Fix Windows build (signal handling)

### PR DESCRIPTION
**Pull request by theohax**
This should fix the [build error seen here](https://github.com/nanocurrency/nano-node/runs/3942518654?check_suite_focus=true#step:5:943)

### CODE REVIEW

**Comment by dsiganos** [comment]
Theo, do you know why this doesn't this work on Windows?

**Comment by theohax** [comment]
> Theo, do you know why this doesn't this work on Windows?

Because it's using UNIX signals. `sigaction` seems to be a problem as well, it might work with the plain old `signal()` function but I haven't tested that. First trying to get the build working, then we'll see if it's still possible to keep this signal handling in an Windows-equivalent form.

**Comment by dsiganos** [comment]
I believe that windows is able to handle to SIGV and SIGABRT. We just need to find out how to do on windows.
Previously we used to use to plain old signal() function. That must have worked on windows too.

**Comment by theohax** [comment]
> I believe that windows is able to handle to SIGV and SIGABRT. We just need to find out how to do on windows. Previously we used to use to plain old signal() function. That must have worked on windows too.

As I said, I believe too that `signal` might work. Let us get the build green, we'll then worry about the handling.

**Comment by dsiganos** [comment]
OK

**Review by dsiganos — APPROVED** [review]

**Pull request merged**
