### PR TITLE
Remove final vote canary code as final votes are now always enabled.

### PR DESCRIPTION
**Pull request by clemahieu**

### CODE REVIEW

**Comment by dsiganos** [comment]
Will this interfere with our test setups? I think they issue canary blocks.
@gr0vity-dev

**Comment by dsiganos** [comment]
The following variables can also be removed:
* live_canary_public_key_data
* beta_canary_public_key_data
* test_canary_public_key_data

**Review by pwojcikdev — DISMISSED** [review]

**Comment by gr0vity-dev** [comment]
I wondered the same, however I like seeing old code removed from the codebase.
The local test networks use pre made ledger mostly. In case we need to create a new ledger we can always initialise the network with an older version and upgrade the db.

What about resetting the beta network ? Will that still work, since we used to issue a canary block in that event.

**Comment by clemahieu** [comment]
It should have no effect, the blocks should simply be treated like normal.

Though it would be good to test this.

**Comment by gr0vity-dev** [comment]
I tested the changes in a local network :
- **Without a canary** block in the ledger
  - With **this PR** an election is only confirmed **after 2 rounds of voting**
  - With  **V26.1** an election is confirmed **after 1 round of voting**
- **With a canary** in the ledger (for the sake of completeness)
  - **both versions** require **2 rounds of voting**

Screenshot 2024-03-19 at 12 24 38

**Pull request merged**
