### PR TITLE
Removed all unnecessary usings

### PR DESCRIPTION
**Pull request by RickiNano**
Removed unnecessary usings from the node project.
Compiled and tested manually.
Unit tests completed successfully

### CODE REVIEW

**Comment by dsiganos** [comment]
Did you use an automated process to remove them?

**Comment by RickiNano** [comment]
@dsiganos 
Yes. I used the c++ resharper plugin for Visual Studio

**Comment by dsiganos** [comment]
Do you know how it decides if an include is needed or not?
How does it deal with #ifdefs?

**Comment by RickiNano** [comment]
I don't know how it checks if a using is needed but it seems to have done a good job

**Pull request merged**
