### PR TITLE
Add optional offset parameter for the receivable RPC

### LINKED ISSUE #3699: Add optional offset parameter for the receivable RPC
### Summary

There is currently no way to request receivable blocks in chunks. Getting all receivable blocks of addresses like the famous burn address `nano_1111111111111111111111111111111111111111111111111111hifc8npp` is hell, because the response body is too huge for some system and/or software environments, which leads to either request timeouts or exceeding of the configured max HTTP body size. A new offset parameter would provide an alternative method to request these receivable blocks in chunks.

### What problem would be solved by this feature?

Adding the possibility to request receivable blocks in chunks would help to avoid request timeouts and/or exceeding of the configured max HTTP body size.

### Are there any previous requests for this feature?

Not that I'm aware of.

### Do you have a suggested solution?

Yes, a new offset parameter for the receivable RPC would allow to request receivable blocks in chunks and solve this issue.

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would

### Possible solution

I will create a PR.

### Supporting files

_No response_

### PR DESCRIPTION
**Pull request by Exxenoz**
Closes #3699

### CODE REVIEW

**Comment by Exxenoz** [comment]
@dsiganos I forgot to add some small tweaks to the sorting case. Build and tests should be working now.

**Review by clemahieu — APPROVED** [review]

**Comment by dsiganos** [comment]
This looks good but we should really have a unit test for this too.

**Comment by zhyatt** [comment]
> This looks good but we should really have a unit test for this too.

@dsiganos Is the unit test done here https://github.com/nanocurrency/nano-node/pull/3700/files#diff-b053a0c38b909565d0ba60ffdfec20e375bb648c815b8088b9c51e6ed22cc71cR1862 incomplete or need to be broken out into a separate test?

**Comment by dsiganos** [comment]
Doh! I missed that! We are good.

**Pull request merged**
