### PR TITLE
Fix cmake-format-all.sh script + friendlier xargs usage

### PR DESCRIPTION
**Pull request by theohax**
@cryptocode @clemahieu let me know guys if `./ci/clang-format-all.sh` and especially `./ci/cmake-format-all.sh` run fine on your Macbooks. Just tested on mine and looks good.

### CODE REVIEW

**Comment by cryptocode** [comment]
This makes the cmake related scripts execute, but running `ci/check-cmake-format.sh` after `ci/cmake-format-all.sh` still results in `Code formatting differs from expected - please run \n\t'bash ci/cmake-format-all.sh'`

**Comment by theohax** [comment]
> This makes the cmake related scripts execute, but running `ci/check-cmake-format.sh` after `ci/cmake-format-all.sh` still results in `Code formatting differs from expected - please run \n\t'bash ci/cmake-format-all.sh'`

Thanks for reporting, I haven't looked into that one but will and then update this accordingly!

**Comment by theohax** [comment]
@cryptocode Both checks seem happy when done by the CI following the last commit. Could you run the check scripts on your OSX locally as well?

```
Run ci/check-commit-format.sh
Detected 'clang-format' with version 'Ubuntu clang-format version 11.0.0-2~ubuntu20.04.1'  (different than '12'), skipping it.
Using 'clang-format-12' version '12'
clang-format passed
```

```
Run bash ci/check-cmake-format.sh
Using 'cmake-format' version '0.6.13'
cmake-format passed
```

**Comment by cryptocode** [comment]
I now get `Unable to run script: working directory not clean (see git status)` on a fresh checkout due to 

```
git status
	modified:   miniupnp (modified content, untracked content)
	modified:   rocksdb (modified content)
```
I haven't actually modified anything manually there, but I think running CMake does affect makefiles in submodules.

But shouldn't these check scripts work on dirty working copies anyway? For instance, I check clang formatting before committing (I have a pre-commit hook so I don't forget)

**Comment by theohax** [comment]
> I now get `Unable to run script: working directory not clean (see git status)` on a fresh checkout due to
> 
> ```
> git status
> 	modified:   miniupnp (modified content, untracked content)
> 	modified:   rocksdb (modified content)
> ```
> 
> I haven't actually modified anything manually there, but I think running CMake does affect makefiles in submodules.
> 
> But shouldn't these check scripts work on dirty working copies anyway? For instance, I check clang formatting before committing (I have a pre-commit hook so I don't forget)

Hi @cryptocode, after redesigning the scripts I changed that behaviour so that you'd be able to "update/do/perform" formatting via the script at anytime, but you'd only be able to "check" if the formatting is right when in a clean `git status` state. That's because the "check" step is actually doing the same "update" step and then a `git diff` to tell if you were alright or not.

But after seeing your pre-commit hook argument and thinking more about it, I realised the "check" step is definitely not robust. So I've already re-redesigned the "doing" and the "checking" steps for both clang and cmake, but I'd rather put that up in a different PR in order to keep things clean and tidy. Would you mind approving this as-is, getting it in, so that I can open the subsequent one and you can have a look at how the new mechanism works?

Thanks for your valuable reports btw!

**Review by cryptocode — APPROVED** [review]

**Comment by theohax** [comment]
Thanks for approving, new PR is https://github.com/nanocurrency/nano-node/pull/3486

**Pull request merged**
