### PR TITLE
Handle SIGABRT and SIGSEGV on Windows

### PR DESCRIPTION
**Pull request by theohax**
Follow-up of https://github.com/nanocurrency/nano-node/pull/3509

@dsiganos I think this is how you were thinking to do it as well, right? Curious to see if the CI is green on Windows. It used to be like that a while ago so it should be fine I hope.

### CODE REVIEW

**Comment by dsiganos** [comment]
Yes, this is probably good enough.
Alternatively, we could use signal() everywhere although it is supposedly deprecated for sigaction.

**Comment by dsiganos** [comment]
We just need to make sure we do not enter into a signal raising loop.
When using signal() function what will do the equivalent of SA_RESETHAND?

**Comment by dsiganos** [comment]
This is what the old signal handler used to do:
```
void my_abort_signal_handler (int signum)
{
	std::signal (signum, SIG_DFL);
	nano::dump_crash_stacktrace ();
	nano::create_load_memory_address_files ();
}
```

So, we maybe need to call `std::signal (signum, SIG_DFL)` inside the signal handler when in windows.

**Comment by dsiganos** [comment]
I think what was happening with the old signal handler was this:
* The signal handler was executed and it removed it self from the signal handling
* then it saved the stack trace and returned
* the program re-tries  the last operation and it fails again and raises the signal again but this time the default signals is executed and the program ends

**Comment by theohax** [comment]
@dsiganos alright, sounds good, incorporated that feedback into the last commit, please have another look. Thanks.

**Review by dsiganos — APPROVED** [review]

**Pull request merged**
