### PR TITLE
Configurable work watcher period

### PR DESCRIPTION
**Pull request by guilhermelawless**
New option `work_watcher_period` defaulting to 5 seconds.

Also moved the `condition.wait` to the end of the loop so that `stopped` is checked before going through blocks.

### CODE REVIEW

**Comment by SergiySW** [comment]
Are all timings in config currently in ms?

**Comment by guilhermelawless** [comment]
I believe so, but documentation covers it. Do we need that much control?

**Comment by guilhermelawless** [comment]
@SergiySW there are 2 instances of times in seconds: `tcp_io_timeout` and IPC transport `timeout`.

**Comment by SergiySW** [comment]
I guess we need check for it to not be 0?

**Comment by cryptocode** [comment]
@guilhermelawless for the toml PR: could you attach a comment here with a suitable one-liner description of the new config option? No need to mention data type or default value as the toml file will contain those.

**Comment by guilhermelawless** [comment]
@cryptocode it's best to refer to the nano-docs [PR](https://github.com/nanocurrency/nano-docs/pull/91) in case it changes. That's a one liner in the config documentation.

**Pull request merged**
