### PR TITLE
Submodules

### PR DESCRIPTION
**Pull request by steampunkkoala**
move all submodules into one directory

### CODE REVIEW

**Comment by dsiganos** [comment]
Thank you for doing this. We will look into merging this after the upcoming release because now it would be too risky to merge.

**Comment by thsfs** [comment]
Thanks for the suggestion. My opinion is I'd rather name it as "third_party" as they are not submodules, but third-party code.

**Comment by dsiganos** [comment]
He had it as third party and I asked him to rename it to submodules because it seemed more correct.
Not all submodules are third party.

**Comment by steampunkkoala** [comment]
it currently has only git submodules, it might be worth having a 3rd party directory as there is folder like CL that is 3rd party that is not a submodule

**Comment by steampunkkoala** [comment]
in some ways it would be nice to also have all the code under one folder, which is basically the nano folder now. It could basically be renamed to source and everything source code related could be moved under it.

**Comment by thsfs** [comment]
1. The node itself is composed by multiple parts we have not been able yet to have them in a fully containerized implementation (in a loose coupling way) that we could then name it as submodule. But understand if we pick the git submodule way to name it.
2. Having a source folder seems good.

I'd just avoid the Pascal/camelCase pattern as we preferred the snake_case.

**Comment by steampunkkoala** [comment]
I am use to my projects using camel case, so I default to that, but I understand this project uses snake_case so I will try my best to keep it inline with how things are, and if I accidently use camel case, feel free to point it out so I can fix it.

would like to have something like this

root
    - ci
    - docker
    - source
    -- third_party
    --- CL
    --- ...
    --  submodules
    --- cpptoml
    --- ...
    -- node
     --- ...

Although restructuring everything at once is a huge change, better to just move small bits at a time and make sure things are still working correctly

**Comment by dsiganos** [comment]
This would be a good time to finish this. Can we rebase on top of latest develop branch and retest it?

**Comment by steampunkkoala** [comment]
I have redone this pull request with the latest code
https://github.com/nanocurrency/nano-node/pull/4062

**Pull request closed without merging**
